
random_state: 42
target: arrival_delay_minutes
positive_delay_threshold: 15   # minutes
test_size: 0.2
val_size: 0.1
models:
  - name: xgboost
    params:
      n_estimators: 400
      max_depth: 6
      learning_rate: 0.08
      subsample: 0.9
      colsample_bytree: 0.9
  - name: lightgbm
    params:
      n_estimators: 600
      num_leaves: 64
      learning_rate: 0.04
      subsample: 0.9
      colsample_bytree: 0.9
